### PR TITLE
cJSON update

### PR DESCRIPTION
**Pull request by benlachman**

### CODE REVIEW

**Comment by benlachman** [comment]
@mploof We might want to pull in the 1.2.1 update from https://github.com/DaveGamble/cJSON/releases/tag/v1.2.1

**Comment by RobinKinney** [comment]
Won't we start pulling this since it is referenced by subtrees?

**Comment by RobinKinney** [comment]
I'm still trying to get my head around subtrees but I don't want to begin using the new cJSON until we have taken the time to test the features that causes the version we're currently using to crash.

**Comment by RobinKinney** [comment]
I'm always confused by the difference in the language. Some places it's referring to this pull request as merging develop into cjson-update and others it's cjson-update into develop.

**Comment by benlachman** [comment]
@RobinKinney This version has vastly better code readability and a whole load of bug fixes. This branch has been waiting since the beginning of December. Once it's merged into VendorEmbedded/Develop, you can get that update by pulling the subtree. It will not automagically be pushed into repositories that depend on it since that would be bad ;-)

**Pull request merged**
